//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.30 at 01:01:40 PM MESZ 
//


package com.setantamedia.fulcrum.microsoft.office.onenote.custom.tim;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="section" type="{}section" minOccurs="0"/>
 *         &lt;element name="sectiongroup" type="{}sectiongroup" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="module" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="subtype" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="meetingday" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="meetingmonth" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="meetingyear" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "section",
    "sectiongroup"
})
@XmlRootElement(name = "notebook")
public class Notebook {

    protected Section section;
    @XmlElement(required = true)
    protected List<Sectiongroup> sectiongroup;
    @XmlAttribute
    protected String id;
    @XmlAttribute
    protected String title;
    @XmlAttribute
    protected String module;
    @XmlAttribute
    protected String subtype;
    @XmlAttribute
    protected String meetingday;
    @XmlAttribute
    protected String meetingmonth;
    @XmlAttribute
    protected String meetingyear;

    /**
     * Gets the value of the section property.
     * 
     * @return
     *     possible object is
     *     {@link Section }
     *     
     */
    public Section getSection() {
        return section;
    }

    /**
     * Sets the value of the section property.
     * 
     * @param value
     *     allowed object is
     *     {@link Section }
     *     
     */
    public void setSection(Section value) {
        this.section = value;
    }

    /**
     * Gets the value of the sectiongroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sectiongroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSectiongroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sectiongroup }
     * 
     * 
     */
    public List<Sectiongroup> getSectiongroup() {
        if (sectiongroup == null) {
            sectiongroup = new ArrayList<Sectiongroup>();
        }
        return this.sectiongroup;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the module property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModule() {
        return module;
    }

    /**
     * Sets the value of the module property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModule(String value) {
        this.module = value;
    }

    /**
     * Gets the value of the subtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubtype() {
        return subtype;
    }

    /**
     * Sets the value of the subtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubtype(String value) {
        this.subtype = value;
    }

    /**
     * Gets the value of the meetingday property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeetingday() {
        return meetingday;
    }

    /**
     * Sets the value of the meetingday property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeetingday(String value) {
        this.meetingday = value;
    }

    /**
     * Gets the value of the meetingmonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeetingmonth() {
        return meetingmonth;
    }

    /**
     * Sets the value of the meetingmonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeetingmonth(String value) {
        this.meetingmonth = value;
    }

    /**
     * Gets the value of the meetingyear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeetingyear() {
        return meetingyear;
    }

    /**
     * Sets the value of the meetingyear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeetingyear(String value) {
        this.meetingyear = value;
    }

}
