//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.29 at 12:41:31 PM CET 
//


package com.setantamedia.fulcrum.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dam complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dam">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dataFolder" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="schemaFile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customSchemaFile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="baseUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="managerClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="imageToolPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="metadataToolPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="connections" type="{}connectionList"/>
 *         &lt;element name="views" type="{}viewList" minOccurs="0"/>
 *         &lt;element name="params" type="{}paramList" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dam", propOrder = {
    "dataFolder",
    "schemaFile",
    "customSchemaFile",
    "baseUrl",
    "managerClass",
    "imageToolPath",
    "metadataToolPath",
    "connections",
    "views",
    "params"
})
public class Dam {

    protected String dataFolder;
    protected String schemaFile;
    protected String customSchemaFile;
    @XmlElement(required = true)
    protected String baseUrl;
    @XmlElement(required = true)
    protected String managerClass;
    protected String imageToolPath;
    protected String metadataToolPath;
    @XmlElement(required = true)
    protected ConnectionList connections;
    protected ViewList views;
    protected ParamList params;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the dataFolder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataFolder() {
        return dataFolder;
    }

    /**
     * Sets the value of the dataFolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataFolder(String value) {
        this.dataFolder = value;
    }

    /**
     * Gets the value of the schemaFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaFile() {
        return schemaFile;
    }

    /**
     * Sets the value of the schemaFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaFile(String value) {
        this.schemaFile = value;
    }

    /**
     * Gets the value of the customSchemaFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomSchemaFile() {
        return customSchemaFile;
    }

    /**
     * Sets the value of the customSchemaFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomSchemaFile(String value) {
        this.customSchemaFile = value;
    }

    /**
     * Gets the value of the baseUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseUrl() {
        return baseUrl;
    }

    /**
     * Sets the value of the baseUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseUrl(String value) {
        this.baseUrl = value;
    }

    /**
     * Gets the value of the managerClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagerClass() {
        return managerClass;
    }

    /**
     * Sets the value of the managerClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagerClass(String value) {
        this.managerClass = value;
    }

    /**
     * Gets the value of the imageToolPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageToolPath() {
        return imageToolPath;
    }

    /**
     * Sets the value of the imageToolPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageToolPath(String value) {
        this.imageToolPath = value;
    }

    /**
     * Gets the value of the metadataToolPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetadataToolPath() {
        return metadataToolPath;
    }

    /**
     * Sets the value of the metadataToolPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetadataToolPath(String value) {
        this.metadataToolPath = value;
    }

    /**
     * Gets the value of the connections property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectionList }
     *     
     */
    public ConnectionList getConnections() {
        return connections;
    }

    /**
     * Sets the value of the connections property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectionList }
     *     
     */
    public void setConnections(ConnectionList value) {
        this.connections = value;
    }

    /**
     * Gets the value of the views property.
     * 
     * @return
     *     possible object is
     *     {@link ViewList }
     *     
     */
    public ViewList getViews() {
        return views;
    }

    /**
     * Sets the value of the views property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViewList }
     *     
     */
    public void setViews(ViewList value) {
        this.views = value;
    }

    /**
     * Gets the value of the params property.
     * 
     * @return
     *     possible object is
     *     {@link ParamList }
     *     
     */
    public ParamList getParams() {
        return params;
    }

    /**
     * Sets the value of the params property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParamList }
     *     
     */
    public void setParams(ParamList value) {
        this.params = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
