//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.29 at 12:41:31 PM CET 
//


package com.setantamedia.fulcrum.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="log4jConfigPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="docroot" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="adminPassword" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="serverPort" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="serverThreads" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="startWebservice" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="startFilewatcher" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="tmpFolder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="previewCacheFolder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="useDam" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="serverPrefix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dams" type="{}damList" minOccurs="0"/>
 *         &lt;element name="databases" type="{}databaseList" minOccurs="0"/>
 *         &lt;element name="previews" type="{}previewList" minOccurs="0"/>
 *         &lt;element name="queries" type="{}queryList" minOccurs="0"/>
 *         &lt;element name="locations" type="{}locationList" minOccurs="0"/>
 *         &lt;element name="actions" type="{}actionList" minOccurs="0"/>
 *         &lt;element name="workflows" type="{}workflowList" minOccurs="0"/>
 *         &lt;element name="mailServer" type="{}mailServer" minOccurs="0"/>
 *         &lt;element name="mydam" type="{}mydam" minOccurs="0"/>
 *         &lt;element name="servlets" type="{}servletList" minOccurs="0"/>
 *         &lt;element name="messageBrokers" type="{}messageBrokerList" minOccurs="0"/>
 *         &lt;element name="woodwing" type="{}woodwingConfig" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "log4JConfigPath",
    "docroot",
    "adminPassword",
    "serverPort",
    "serverThreads",
    "startWebservice",
    "startFilewatcher",
    "tmpFolder",
    "previewCacheFolder",
    "useDam",
    "serverPrefix",
    "dams",
    "databases",
    "previews",
    "queries",
    "locations",
    "actions",
    "workflows",
    "mailServer",
    "mydam",
    "servlets",
    "messageBrokers",
    "woodwing"
})
@XmlRootElement(name = "fulcrumConfig")
public class FulcrumConfig {

    @XmlElement(name = "log4jConfigPath")
    protected String log4JConfigPath;
    @XmlElement(required = true)
    protected String docroot;
    @XmlElement(required = true)
    protected String adminPassword;
    protected int serverPort;
    @XmlElement(required = true)
    protected String serverThreads;
    protected boolean startWebservice;
    protected boolean startFilewatcher;
    @XmlElement(required = true)
    protected String tmpFolder;
    @XmlElement(required = true)
    protected String previewCacheFolder;
    protected String useDam;
    protected String serverPrefix;
    protected DamList dams;
    protected DatabaseList databases;
    protected PreviewList previews;
    protected QueryList queries;
    protected LocationList locations;
    protected ActionList actions;
    protected WorkflowList workflows;
    protected MailServer mailServer;
    protected Mydam mydam;
    protected ServletList servlets;
    protected MessageBrokerList messageBrokers;
    protected WoodwingConfig woodwing;

    /**
     * Gets the value of the log4JConfigPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLog4JConfigPath() {
        return log4JConfigPath;
    }

    /**
     * Sets the value of the log4JConfigPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLog4JConfigPath(String value) {
        this.log4JConfigPath = value;
    }

    /**
     * Gets the value of the docroot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocroot() {
        return docroot;
    }

    /**
     * Sets the value of the docroot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocroot(String value) {
        this.docroot = value;
    }

    /**
     * Gets the value of the adminPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdminPassword() {
        return adminPassword;
    }

    /**
     * Sets the value of the adminPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdminPassword(String value) {
        this.adminPassword = value;
    }

    /**
     * Gets the value of the serverPort property.
     * 
     */
    public int getServerPort() {
        return serverPort;
    }

    /**
     * Sets the value of the serverPort property.
     * 
     */
    public void setServerPort(int value) {
        this.serverPort = value;
    }

    /**
     * Gets the value of the serverThreads property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServerThreads() {
        return serverThreads;
    }

    /**
     * Sets the value of the serverThreads property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerThreads(String value) {
        this.serverThreads = value;
    }

    /**
     * Gets the value of the startWebservice property.
     * 
     */
    public boolean isStartWebservice() {
        return startWebservice;
    }

    /**
     * Sets the value of the startWebservice property.
     * 
     */
    public void setStartWebservice(boolean value) {
        this.startWebservice = value;
    }

    /**
     * Gets the value of the startFilewatcher property.
     * 
     */
    public boolean isStartFilewatcher() {
        return startFilewatcher;
    }

    /**
     * Sets the value of the startFilewatcher property.
     * 
     */
    public void setStartFilewatcher(boolean value) {
        this.startFilewatcher = value;
    }

    /**
     * Gets the value of the tmpFolder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTmpFolder() {
        return tmpFolder;
    }

    /**
     * Sets the value of the tmpFolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTmpFolder(String value) {
        this.tmpFolder = value;
    }

    /**
     * Gets the value of the previewCacheFolder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreviewCacheFolder() {
        return previewCacheFolder;
    }

    /**
     * Sets the value of the previewCacheFolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreviewCacheFolder(String value) {
        this.previewCacheFolder = value;
    }

    /**
     * Gets the value of the useDam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUseDam() {
        return useDam;
    }

    /**
     * Sets the value of the useDam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUseDam(String value) {
        this.useDam = value;
    }

    /**
     * Gets the value of the serverPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServerPrefix() {
        return serverPrefix;
    }

    /**
     * Sets the value of the serverPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerPrefix(String value) {
        this.serverPrefix = value;
    }

    /**
     * Gets the value of the dams property.
     * 
     * @return
     *     possible object is
     *     {@link DamList }
     *     
     */
    public DamList getDams() {
        return dams;
    }

    /**
     * Sets the value of the dams property.
     * 
     * @param value
     *     allowed object is
     *     {@link DamList }
     *     
     */
    public void setDams(DamList value) {
        this.dams = value;
    }

    /**
     * Gets the value of the databases property.
     * 
     * @return
     *     possible object is
     *     {@link DatabaseList }
     *     
     */
    public DatabaseList getDatabases() {
        return databases;
    }

    /**
     * Sets the value of the databases property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatabaseList }
     *     
     */
    public void setDatabases(DatabaseList value) {
        this.databases = value;
    }

    /**
     * Gets the value of the previews property.
     * 
     * @return
     *     possible object is
     *     {@link PreviewList }
     *     
     */
    public PreviewList getPreviews() {
        return previews;
    }

    /**
     * Sets the value of the previews property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreviewList }
     *     
     */
    public void setPreviews(PreviewList value) {
        this.previews = value;
    }

    /**
     * Gets the value of the queries property.
     * 
     * @return
     *     possible object is
     *     {@link QueryList }
     *     
     */
    public QueryList getQueries() {
        return queries;
    }

    /**
     * Sets the value of the queries property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryList }
     *     
     */
    public void setQueries(QueryList value) {
        this.queries = value;
    }

    /**
     * Gets the value of the locations property.
     * 
     * @return
     *     possible object is
     *     {@link LocationList }
     *     
     */
    public LocationList getLocations() {
        return locations;
    }

    /**
     * Sets the value of the locations property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationList }
     *     
     */
    public void setLocations(LocationList value) {
        this.locations = value;
    }

    /**
     * Gets the value of the actions property.
     * 
     * @return
     *     possible object is
     *     {@link ActionList }
     *     
     */
    public ActionList getActions() {
        return actions;
    }

    /**
     * Sets the value of the actions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionList }
     *     
     */
    public void setActions(ActionList value) {
        this.actions = value;
    }

    /**
     * Gets the value of the workflows property.
     * 
     * @return
     *     possible object is
     *     {@link WorkflowList }
     *     
     */
    public WorkflowList getWorkflows() {
        return workflows;
    }

    /**
     * Sets the value of the workflows property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkflowList }
     *     
     */
    public void setWorkflows(WorkflowList value) {
        this.workflows = value;
    }

    /**
     * Gets the value of the mailServer property.
     * 
     * @return
     *     possible object is
     *     {@link MailServer }
     *     
     */
    public MailServer getMailServer() {
        return mailServer;
    }

    /**
     * Sets the value of the mailServer property.
     * 
     * @param value
     *     allowed object is
     *     {@link MailServer }
     *     
     */
    public void setMailServer(MailServer value) {
        this.mailServer = value;
    }

    /**
     * Gets the value of the mydam property.
     * 
     * @return
     *     possible object is
     *     {@link Mydam }
     *     
     */
    public Mydam getMydam() {
        return mydam;
    }

    /**
     * Sets the value of the mydam property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mydam }
     *     
     */
    public void setMydam(Mydam value) {
        this.mydam = value;
    }

    /**
     * Gets the value of the servlets property.
     * 
     * @return
     *     possible object is
     *     {@link ServletList }
     *     
     */
    public ServletList getServlets() {
        return servlets;
    }

    /**
     * Sets the value of the servlets property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServletList }
     *     
     */
    public void setServlets(ServletList value) {
        this.servlets = value;
    }

    /**
     * Gets the value of the messageBrokers property.
     * 
     * @return
     *     possible object is
     *     {@link MessageBrokerList }
     *     
     */
    public MessageBrokerList getMessageBrokers() {
        return messageBrokers;
    }

    /**
     * Sets the value of the messageBrokers property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageBrokerList }
     *     
     */
    public void setMessageBrokers(MessageBrokerList value) {
        this.messageBrokers = value;
    }

    /**
     * Gets the value of the woodwing property.
     * 
     * @return
     *     possible object is
     *     {@link WoodwingConfig }
     *     
     */
    public WoodwingConfig getWoodwing() {
        return woodwing;
    }

    /**
     * Sets the value of the woodwing property.
     * 
     * @param value
     *     allowed object is
     *     {@link WoodwingConfig }
     *     
     */
    public void setWoodwing(WoodwingConfig value) {
        this.woodwing = value;
    }

}
