//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.29 at 12:41:31 PM CET 
//


package com.setantamedia.fulcrum.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mydam complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mydam">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="storageRoot" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="imageTool" type="{}imageTool"/>
 *         &lt;element name="metadataTool" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pdfTool" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mydam", propOrder = {
    "storageRoot",
    "imageTool",
    "metadataTool",
    "pdfTool"
})
public class Mydam {

    @XmlElement(required = true)
    protected String storageRoot;
    @XmlElement(required = true)
    protected ImageTool imageTool;
    @XmlElement(required = true)
    protected String metadataTool;
    @XmlElement(required = true)
    protected String pdfTool;

    /**
     * Gets the value of the storageRoot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStorageRoot() {
        return storageRoot;
    }

    /**
     * Sets the value of the storageRoot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStorageRoot(String value) {
        this.storageRoot = value;
    }

    /**
     * Gets the value of the imageTool property.
     * 
     * @return
     *     possible object is
     *     {@link ImageTool }
     *     
     */
    public ImageTool getImageTool() {
        return imageTool;
    }

    /**
     * Sets the value of the imageTool property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageTool }
     *     
     */
    public void setImageTool(ImageTool value) {
        this.imageTool = value;
    }

    /**
     * Gets the value of the metadataTool property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetadataTool() {
        return metadataTool;
    }

    /**
     * Sets the value of the metadataTool property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetadataTool(String value) {
        this.metadataTool = value;
    }

    /**
     * Gets the value of the pdfTool property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPdfTool() {
        return pdfTool;
    }

    /**
     * Sets the value of the pdfTool property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPdfTool(String value) {
        this.pdfTool = value;
    }

}
