//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.29 at 12:41:31 PM CET 
//


package com.setantamedia.fulcrum.config;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.setantamedia.fulcrum.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.setantamedia.fulcrum.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FulcrumConfig }
     * 
     */
    public FulcrumConfig createFulcrumConfig() {
        return new FulcrumConfig();
    }

    /**
     * Create an instance of {@link DamList }
     * 
     */
    public DamList createDamList() {
        return new DamList();
    }

    /**
     * Create an instance of {@link DatabaseList }
     * 
     */
    public DatabaseList createDatabaseList() {
        return new DatabaseList();
    }

    /**
     * Create an instance of {@link PreviewList }
     * 
     */
    public PreviewList createPreviewList() {
        return new PreviewList();
    }

    /**
     * Create an instance of {@link QueryList }
     * 
     */
    public QueryList createQueryList() {
        return new QueryList();
    }

    /**
     * Create an instance of {@link LocationList }
     * 
     */
    public LocationList createLocationList() {
        return new LocationList();
    }

    /**
     * Create an instance of {@link ActionList }
     * 
     */
    public ActionList createActionList() {
        return new ActionList();
    }

    /**
     * Create an instance of {@link WorkflowList }
     * 
     */
    public WorkflowList createWorkflowList() {
        return new WorkflowList();
    }

    /**
     * Create an instance of {@link MailServer }
     * 
     */
    public MailServer createMailServer() {
        return new MailServer();
    }

    /**
     * Create an instance of {@link Mydam }
     * 
     */
    public Mydam createMydam() {
        return new Mydam();
    }

    /**
     * Create an instance of {@link ServletList }
     * 
     */
    public ServletList createServletList() {
        return new ServletList();
    }

    /**
     * Create an instance of {@link MessageBrokerList }
     * 
     */
    public MessageBrokerList createMessageBrokerList() {
        return new MessageBrokerList();
    }

    /**
     * Create an instance of {@link WoodwingConfig }
     * 
     */
    public WoodwingConfig createWoodwingConfig() {
        return new WoodwingConfig();
    }

    /**
     * Create an instance of {@link SortRule }
     * 
     */
    public SortRule createSortRule() {
        return new SortRule();
    }

    /**
     * Create an instance of {@link ConnectionList }
     * 
     */
    public ConnectionList createConnectionList() {
        return new ConnectionList();
    }

    /**
     * Create an instance of {@link TopicList }
     * 
     */
    public TopicList createTopicList() {
        return new TopicList();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link Query }
     * 
     */
    public Query createQuery() {
        return new Query();
    }

    /**
     * Create an instance of {@link AccessControl }
     * 
     */
    public AccessControl createAccessControl() {
        return new AccessControl();
    }

    /**
     * Create an instance of {@link ParamList }
     * 
     */
    public ParamList createParamList() {
        return new ParamList();
    }

    /**
     * Create an instance of {@link ViewList }
     * 
     */
    public ViewList createViewList() {
        return new ViewList();
    }

    /**
     * Create an instance of {@link Action }
     * 
     */
    public Action createAction() {
        return new Action();
    }

    /**
     * Create an instance of {@link MessageBroker }
     * 
     */
    public MessageBroker createMessageBroker() {
        return new MessageBroker();
    }

    /**
     * Create an instance of {@link Topic }
     * 
     */
    public Topic createTopic() {
        return new Topic();
    }

    /**
     * Create an instance of {@link Connection }
     * 
     */
    public Connection createConnection() {
        return new Connection();
    }

    /**
     * Create an instance of {@link Monitor }
     * 
     */
    public Monitor createMonitor() {
        return new Monitor();
    }

    /**
     * Create an instance of {@link Workflow }
     * 
     */
    public Workflow createWorkflow() {
        return new Workflow();
    }

    /**
     * Create an instance of {@link Database }
     * 
     */
    public Database createDatabase() {
        return new Database();
    }

    /**
     * Create an instance of {@link Servlet }
     * 
     */
    public Servlet createServlet() {
        return new Servlet();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link Preview }
     * 
     */
    public Preview createPreview() {
        return new Preview();
    }

    /**
     * Create an instance of {@link Dam }
     * 
     */
    public Dam createDam() {
        return new Dam();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link ImageTool }
     * 
     */
    public ImageTool createImageTool() {
        return new ImageTool();
    }

    /**
     * Create an instance of {@link View }
     * 
     */
    public View createView() {
        return new View();
    }

}
