
package damchalcoapi.soap.admin;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Metadata", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://tablet.chalco.net/WWCNWS/IDB/Metadata/Metadata.asmx?WSDL")
public class Metadata
    extends Service
{

    private final static URL METADATA_WSDL_LOCATION;
    private final static WebServiceException METADATA_EXCEPTION;
    private final static QName METADATA_QNAME = new QName("http://tempuri.org/", "Metadata");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://tablet.chalco.net/WWCNWS/IDB/Metadata/Metadata.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        METADATA_WSDL_LOCATION = url;
        METADATA_EXCEPTION = e;
    }

    public Metadata() {
        super(__getWsdlLocation(), METADATA_QNAME);
    }

    public Metadata(WebServiceFeature... features) {
        super(__getWsdlLocation(), METADATA_QNAME, features);
    }

    public Metadata(URL wsdlLocation) {
        super(wsdlLocation, METADATA_QNAME);
    }

    public Metadata(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, METADATA_QNAME, features);
    }

    public Metadata(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Metadata(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MetadataSoap
     */
    @WebEndpoint(name = "MetadataSoap")
    public MetadataSoap getMetadataSoap() {
        return super.getPort(new QName("http://tempuri.org/", "MetadataSoap"), MetadataSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MetadataSoap
     */
    @WebEndpoint(name = "MetadataSoap")
    public MetadataSoap getMetadataSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "MetadataSoap"), MetadataSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (METADATA_EXCEPTION!= null) {
            throw METADATA_EXCEPTION;
        }
        return METADATA_WSDL_LOCATION;
    }

}
