
package damchalcoapi.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AssetSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AssetSoap {


    /**
     * 
     * @param count
     * @param query
     * @param offset
     * @return
     *     returns damchalcoapi.soap.ArrayOfResponseOfAsset
     */
    @WebMethod(operationName = "TextSearch", action = "http://tempuri.org/TextSearch")
    @WebResult(name = "TextSearchResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TextSearch", targetNamespace = "http://tempuri.org/", className = "damchalcoapi.soap.TextSearch")
    @ResponseWrapper(localName = "TextSearchResponse", targetNamespace = "http://tempuri.org/", className = "damchalcoapi.soap.TextSearchResponse")
    public ArrayOfResponseOfAsset textSearch(
        @WebParam(name = "query", targetNamespace = "http://tempuri.org/")
        String query,
        @WebParam(name = "offset", targetNamespace = "http://tempuri.org/")
        int offset,
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        int count);

    /**
     * 
     * @param id
     * @param name
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "Preview", action = "http://tempuri.org/Preview")
    @WebResult(name = "PreviewResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Preview", targetNamespace = "http://tempuri.org/", className = "damchalcoapi.soap.Preview")
    @ResponseWrapper(localName = "PreviewResponse", targetNamespace = "http://tempuri.org/", className = "damchalcoapi.soap.PreviewResponse")
    public byte[] preview(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        int id,
        @WebParam(name = "name", targetNamespace = "http://tempuri.org/")
        String name);

    /**
     * 
     * @param id
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "Download", action = "http://tempuri.org/Download")
    @WebResult(name = "DownloadResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Download", targetNamespace = "http://tempuri.org/", className = "damchalcoapi.soap.Download")
    @ResponseWrapper(localName = "DownloadResponse", targetNamespace = "http://tempuri.org/", className = "damchalcoapi.soap.DownloadResponse")
    public byte[] download(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        int id);

}
