
package damchalcoapi.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Asset", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://tablet.chalco.net/WWCNWS/IDB/Assets/Asset.asmx?WSDL")
public class Asset
    extends Service
{

    private final static URL ASSET_WSDL_LOCATION;
    private final static WebServiceException ASSET_EXCEPTION;
    private final static QName ASSET_QNAME = new QName("http://tempuri.org/", "Asset");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://tablet.chalco.net/WWCNWS/IDB/Assets/Asset.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ASSET_WSDL_LOCATION = url;
        ASSET_EXCEPTION = e;
    }

    public Asset() {
        super(__getWsdlLocation(), ASSET_QNAME);
    }

    public Asset(WebServiceFeature... features) {
        super(__getWsdlLocation(), ASSET_QNAME, features);
    }

    public Asset(URL wsdlLocation) {
        super(wsdlLocation, ASSET_QNAME);
    }

    public Asset(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ASSET_QNAME, features);
    }

    public Asset(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Asset(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AssetSoap
     */
    @WebEndpoint(name = "AssetSoap")
    public AssetSoap getAssetSoap() {
        return super.getPort(new QName("http://tempuri.org/", "AssetSoap"), AssetSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AssetSoap
     */
    @WebEndpoint(name = "AssetSoap")
    public AssetSoap getAssetSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "AssetSoap"), AssetSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ASSET_EXCEPTION!= null) {
            throw ASSET_EXCEPTION;
        }
        return ASSET_WSDL_LOCATION;
    }

}
