//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.26 at 07:40:13 PM MESZ 
//


package com.setantamedia.fulcrum.microsoft.office.onenote;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Collection of settings controlling how contained OEs layout.
 * 			
 * 
 * <p>Java class for ChildOELayout complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChildOELayout">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="spaceBefore" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}PositiveDecimal" />
 *       &lt;attribute name="spaceBetween" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}PositiveDecimal" />
 *       &lt;attribute name="spaceAfter" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}PositiveDecimal" />
 *       &lt;attribute name="listSpacing" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}PositiveDecimal" />
 *       &lt;attribute name="listAlignment">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="left"/>
 *             &lt;enumeration value="right"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChildOELayout")
public class ChildOELayout {

    @XmlAttribute
    protected Double spaceBefore;
    @XmlAttribute
    protected Double spaceBetween;
    @XmlAttribute
    protected Double spaceAfter;
    @XmlAttribute
    protected Double listSpacing;
    @XmlAttribute
    protected String listAlignment;

    /**
     * Gets the value of the spaceBefore property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSpaceBefore() {
        return spaceBefore;
    }

    /**
     * Sets the value of the spaceBefore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSpaceBefore(Double value) {
        this.spaceBefore = value;
    }

    /**
     * Gets the value of the spaceBetween property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSpaceBetween() {
        return spaceBetween;
    }

    /**
     * Sets the value of the spaceBetween property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSpaceBetween(Double value) {
        this.spaceBetween = value;
    }

    /**
     * Gets the value of the spaceAfter property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSpaceAfter() {
        return spaceAfter;
    }

    /**
     * Sets the value of the spaceAfter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSpaceAfter(Double value) {
        this.spaceAfter = value;
    }

    /**
     * Gets the value of the listSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getListSpacing() {
        return listSpacing;
    }

    /**
     * Sets the value of the listSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setListSpacing(Double value) {
        this.listSpacing = value;
    }

    /**
     * Gets the value of the listAlignment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListAlignment() {
        return listAlignment;
    }

    /**
     * Sets the value of the listAlignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListAlignment(String value) {
        this.listAlignment = value;
    }

}
