//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.26 at 07:40:13 PM MESZ 
//


package com.setantamedia.fulcrum.microsoft.office.onenote;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Definition of an image.
 * 
 * 				The data is either referenced in a file or is included inlined, Base64 encoded.
 * 			
 * 
 * <p>Java class for Image complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Image">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.microsoft.com/office/onenote/2010/onenote}PageObjectTagable">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="File" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}FilePath"/>
 *           &lt;element name="Data" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *           &lt;element name="CallbackID" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}CallbackID"/>
 *         &lt;/choice>
 *         &lt;element name="OCRData" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}OCRData" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="format" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}ImageFormat" default="auto" />
 *       &lt;attribute name="xpsFileIndex" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="originalDocumentNumber" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" default="0" />
 *       &lt;attribute name="originalPageNumber" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" default="0" />
 *       &lt;attribute name="isPrintOut" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="backgroundImage" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="hyperlink" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="alt" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Image")
public class Image
    extends PageObjectTagable
{

    @XmlAttribute
    protected String format;
    @XmlAttribute
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger xpsFileIndex;
    @XmlAttribute
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger originalDocumentNumber;
    @XmlAttribute
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger originalPageNumber;
    @XmlAttribute
    protected Boolean isPrintOut;
    @XmlAttribute
    protected Boolean backgroundImage;
    @XmlAttribute
    protected String hyperlink;
    @XmlAttribute
    protected String alt;

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormat() {
        if (format == null) {
            return "auto";
        } else {
            return format;
        }
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormat(String value) {
        this.format = value;
    }

    /**
     * Gets the value of the xpsFileIndex property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getXpsFileIndex() {
        return xpsFileIndex;
    }

    /**
     * Sets the value of the xpsFileIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setXpsFileIndex(BigInteger value) {
        this.xpsFileIndex = value;
    }

    /**
     * Gets the value of the originalDocumentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOriginalDocumentNumber() {
        if (originalDocumentNumber == null) {
            return new BigInteger("0");
        } else {
            return originalDocumentNumber;
        }
    }

    /**
     * Sets the value of the originalDocumentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOriginalDocumentNumber(BigInteger value) {
        this.originalDocumentNumber = value;
    }

    /**
     * Gets the value of the originalPageNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOriginalPageNumber() {
        if (originalPageNumber == null) {
            return new BigInteger("0");
        } else {
            return originalPageNumber;
        }
    }

    /**
     * Sets the value of the originalPageNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOriginalPageNumber(BigInteger value) {
        this.originalPageNumber = value;
    }

    /**
     * Gets the value of the isPrintOut property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsPrintOut() {
        if (isPrintOut == null) {
            return false;
        } else {
            return isPrintOut;
        }
    }

    /**
     * Sets the value of the isPrintOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPrintOut(Boolean value) {
        this.isPrintOut = value;
    }

    /**
     * Gets the value of the backgroundImage property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isBackgroundImage() {
        if (backgroundImage == null) {
            return false;
        } else {
            return backgroundImage;
        }
    }

    /**
     * Sets the value of the backgroundImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBackgroundImage(Boolean value) {
        this.backgroundImage = value;
    }

    /**
     * Gets the value of the hyperlink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHyperlink() {
        return hyperlink;
    }

    /**
     * Sets the value of the hyperlink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHyperlink(String value) {
        this.hyperlink = value;
    }

    /**
     * Gets the value of the alt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlt() {
        return alt;
    }

    /**
     * Sets the value of the alt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlt(String value) {
        this.alt = value;
    }

}
