//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.26 at 07:40:13 PM MESZ 
//


package com.setantamedia.fulcrum.microsoft.office.onenote;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Contains the ink drawing to be imported.  The data is either referenced in a
 * 				file or is included inlined, Base64 encoded.
 * 			
 * 
 * <p>Java class for InkDrawing complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InkDrawing">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.microsoft.com/office/onenote/2010/onenote}PageObjectTagable">
 *       &lt;sequence>
 *         &lt;element name="ShapeInfo" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}ShapeInfo" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="File" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}FilePath"/>
 *           &lt;element name="Data" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *           &lt;element name="CallbackID" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}CallbackID"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="isUnclassified" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="inkOriginX" type="{http://www.w3.org/2001/XMLSchema}double" default="0" />
 *       &lt;attribute name="inkOriginY" type="{http://www.w3.org/2001/XMLSchema}double" default="0" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InkDrawing")
public class InkDrawing
    extends PageObjectTagable
{

    @XmlAttribute
    protected Boolean isUnclassified;
    @XmlAttribute
    protected Double inkOriginX;
    @XmlAttribute
    protected Double inkOriginY;

    /**
     * Gets the value of the isUnclassified property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsUnclassified() {
        if (isUnclassified == null) {
            return false;
        } else {
            return isUnclassified;
        }
    }

    /**
     * Sets the value of the isUnclassified property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsUnclassified(Boolean value) {
        this.isUnclassified = value;
    }

    /**
     * Gets the value of the inkOriginX property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getInkOriginX() {
        if (inkOriginX == null) {
            return  0.0D;
        } else {
            return inkOriginX;
        }
    }

    /**
     * Sets the value of the inkOriginX property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setInkOriginX(Double value) {
        this.inkOriginX = value;
    }

    /**
     * Gets the value of the inkOriginY property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getInkOriginY() {
        if (inkOriginY == null) {
            return  0.0D;
        } else {
            return inkOriginY;
        }
    }

    /**
     * Sets the value of the inkOriginY property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setInkOriginY(Double value) {
        this.inkOriginY = value;
    }

}
