//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.26 at 07:40:13 PM MESZ 
//


package com.setantamedia.fulcrum.microsoft.office.onenote;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Contains the ink word to be imported.  The data is either referenced in a
 * 				file or is included inlined, Base64 encoded.
 * 			
 * 
 * <p>Java class for InkWord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InkWord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="File" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}FilePath"/>
 *         &lt;element name="Data" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="CallbackID" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}CallbackID"/>
 *         &lt;element name="Space" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}Space"/>
 *         &lt;element name="EndOfLine" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}EndOfLine"/>
 *       &lt;/choice>
 *       &lt;attribute name="recognizedText" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="selected" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}Selection" default="none" />
 *       &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="width" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}PositiveDecimal" />
 *       &lt;attribute name="height" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}PositiveDecimal" />
 *       &lt;attribute name="style" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="inkOriginX" type="{http://www.w3.org/2001/XMLSchema}double" default="0" />
 *       &lt;attribute name="inkOriginY" type="{http://www.w3.org/2001/XMLSchema}double" default="0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InkWord", propOrder = {
    "file",
    "data",
    "callbackID",
    "space",
    "endOfLine"
})
public class InkWord {

    @XmlElement(name = "File")
    protected FilePath file;
    @XmlElement(name = "Data")
    protected byte[] data;
    @XmlElement(name = "CallbackID")
    protected CallbackID callbackID;
    @XmlElement(name = "Space")
    protected Space space;
    @XmlElement(name = "EndOfLine")
    protected EndOfLine endOfLine;
    @XmlAttribute
    protected String recognizedText;
    @XmlAttribute
    protected String selected;
    @XmlAttribute
    protected Double x;
    @XmlAttribute
    protected Double y;
    @XmlAttribute
    protected Double width;
    @XmlAttribute
    protected Double height;
    @XmlAttribute
    protected String style;
    @XmlAttribute
    protected Double inkOriginX;
    @XmlAttribute
    protected Double inkOriginY;

    /**
     * Gets the value of the file property.
     * 
     * @return
     *     possible object is
     *     {@link FilePath }
     *     
     */
    public FilePath getFile() {
        return file;
    }

    /**
     * Sets the value of the file property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilePath }
     *     
     */
    public void setFile(FilePath value) {
        this.file = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setData(byte[] value) {
        this.data = ((byte[]) value);
    }

    /**
     * Gets the value of the callbackID property.
     * 
     * @return
     *     possible object is
     *     {@link CallbackID }
     *     
     */
    public CallbackID getCallbackID() {
        return callbackID;
    }

    /**
     * Sets the value of the callbackID property.
     * 
     * @param value
     *     allowed object is
     *     {@link CallbackID }
     *     
     */
    public void setCallbackID(CallbackID value) {
        this.callbackID = value;
    }

    /**
     * Gets the value of the space property.
     * 
     * @return
     *     possible object is
     *     {@link Space }
     *     
     */
    public Space getSpace() {
        return space;
    }

    /**
     * Sets the value of the space property.
     * 
     * @param value
     *     allowed object is
     *     {@link Space }
     *     
     */
    public void setSpace(Space value) {
        this.space = value;
    }

    /**
     * Gets the value of the endOfLine property.
     * 
     * @return
     *     possible object is
     *     {@link EndOfLine }
     *     
     */
    public EndOfLine getEndOfLine() {
        return endOfLine;
    }

    /**
     * Sets the value of the endOfLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndOfLine }
     *     
     */
    public void setEndOfLine(EndOfLine value) {
        this.endOfLine = value;
    }

    /**
     * Gets the value of the recognizedText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecognizedText() {
        return recognizedText;
    }

    /**
     * Sets the value of the recognizedText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecognizedText(String value) {
        this.recognizedText = value;
    }

    /**
     * Gets the value of the selected property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelected() {
        if (selected == null) {
            return "none";
        } else {
            return selected;
        }
    }

    /**
     * Sets the value of the selected property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelected(String value) {
        this.selected = value;
    }

    /**
     * Gets the value of the x property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getX() {
        return x;
    }

    /**
     * Sets the value of the x property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setX(Double value) {
        this.x = value;
    }

    /**
     * Gets the value of the y property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getY() {
        return y;
    }

    /**
     * Sets the value of the y property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setY(Double value) {
        this.y = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWidth(Double value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setHeight(Double value) {
        this.height = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStyle() {
        return style;
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyle(String value) {
        this.style = value;
    }

    /**
     * Gets the value of the inkOriginX property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getInkOriginX() {
        if (inkOriginX == null) {
            return  0.0D;
        } else {
            return inkOriginX;
        }
    }

    /**
     * Sets the value of the inkOriginX property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setInkOriginX(Double value) {
        this.inkOriginX = value;
    }

    /**
     * Gets the value of the inkOriginY property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getInkOriginY() {
        if (inkOriginY == null) {
            return  0.0D;
        } else {
            return inkOriginY;
        }
    }

    /**
     * Sets the value of the inkOriginY property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setInkOriginY(Double value) {
        this.inkOriginY = value;
    }

}
