//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.26 at 07:40:13 PM MESZ 
//


package com.setantamedia.fulcrum.microsoft.office.onenote;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Definition of an InsertedFile.
 * 			
 * 
 * <p>Java class for InsertedFile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InsertedFile">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.microsoft.com/office/onenote/2010/onenote}PageObjectTagable">
 *       &lt;attribute name="pathSource" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pathCache" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="preferredName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InsertedFile")
@XmlSeeAlso({
    MediaFile.class
})
public class InsertedFile
    extends PageObjectTagable
{

    @XmlAttribute
    protected String pathSource;
    @XmlAttribute
    protected String pathCache;
    @XmlAttribute
    protected String preferredName;

    /**
     * Gets the value of the pathSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPathSource() {
        return pathSource;
    }

    /**
     * Sets the value of the pathSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPathSource(String value) {
        this.pathSource = value;
    }

    /**
     * Gets the value of the pathCache property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPathCache() {
        return pathCache;
    }

    /**
     * Sets the value of the pathCache property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPathCache(String value) {
        this.pathCache = value;
    }

    /**
     * Gets the value of the preferredName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferredName() {
        return preferredName;
    }

    /**
     * Sets the value of the preferredName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferredName(String value) {
        this.preferredName = value;
    }

}
