//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.26 at 07:40:13 PM MESZ 
//


package com.setantamedia.fulcrum.microsoft.office.onenote;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				A single instance of an media time stamp.
 * 			
 * 
 * <p>Java class for MediaIndex complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MediaIndex">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MediaReference" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}MediaReference"/>
 *       &lt;/sequence>
 *       &lt;attribute name="timeIndex" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MediaIndex", propOrder = {
    "mediaReference"
})
public class MediaIndex {

    @XmlElement(name = "MediaReference", required = true)
    protected MediaReference mediaReference;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger timeIndex;

    /**
     * Gets the value of the mediaReference property.
     * 
     * @return
     *     possible object is
     *     {@link MediaReference }
     *     
     */
    public MediaReference getMediaReference() {
        return mediaReference;
    }

    /**
     * Sets the value of the mediaReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaReference }
     *     
     */
    public void setMediaReference(MediaReference value) {
        this.mediaReference = value;
    }

    /**
     * Gets the value of the timeIndex property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTimeIndex() {
        return timeIndex;
    }

    /**
     * Sets the value of the timeIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTimeIndex(BigInteger value) {
        this.timeIndex = value;
    }

}
