//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.26 at 07:40:13 PM MESZ 
//


package com.setantamedia.fulcrum.microsoft.office.onenote;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			
 * 
 * <p>Java class for Notebooks complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Notebooks">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Notebook" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}Notebook" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="UnfiledNotes" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}UnfiledNotes" minOccurs="0"/>
 *         &lt;element name="OpenSections" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}OpenSections" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Notebooks", propOrder = {
    "notebook",
    "unfiledNotes",
    "openSections"
})
public class Notebooks {

    @XmlElement(name = "Notebook")
    protected List<Notebook> notebook;
    @XmlElement(name = "UnfiledNotes")
    protected UnfiledNotes unfiledNotes;
    @XmlElement(name = "OpenSections")
    protected OpenSections openSections;

    /**
     * Gets the value of the notebook property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the notebook property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNotebook().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Notebook }
     * 
     * 
     */
    public List<Notebook> getNotebook() {
        if (notebook == null) {
            notebook = new ArrayList<Notebook>();
        }
        return this.notebook;
    }

    /**
     * Gets the value of the unfiledNotes property.
     * 
     * @return
     *     possible object is
     *     {@link UnfiledNotes }
     *     
     */
    public UnfiledNotes getUnfiledNotes() {
        return unfiledNotes;
    }

    /**
     * Sets the value of the unfiledNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnfiledNotes }
     *     
     */
    public void setUnfiledNotes(UnfiledNotes value) {
        this.unfiledNotes = value;
    }

    /**
     * Gets the value of the openSections property.
     * 
     * @return
     *     possible object is
     *     {@link OpenSections }
     *     
     */
    public OpenSections getOpenSections() {
        return openSections;
    }

    /**
     * Sets the value of the openSections property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpenSections }
     *     
     */
    public void setOpenSections(OpenSections value) {
        this.openSections = value;
    }

}
