//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.26 at 07:40:13 PM MESZ 
//


package com.setantamedia.fulcrum.microsoft.office.onenote;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				A collection of outline elements contained within either an outline or an outline element.
 * 			
 * 
 * <p>Java class for OEChildren complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OEChildren">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ChildOELayout" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}ChildOELayout" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="OE" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}OE"/>
 *           &lt;element name="HTMLBlock" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}HtmlContent"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://schemas.microsoft.com/office/onenote/2010/onenote}CascadedTextAttributes"/>
 *       &lt;attribute name="indent" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="1" />
 *       &lt;attribute name="selected" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}Selection" default="none" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OEChildren", propOrder = {
    "childOELayout",
    "oeOrHTMLBlock"
})
public class OEChildren {

    @XmlElement(name = "ChildOELayout")
    protected ChildOELayout childOELayout;
    @XmlElements({
        @XmlElement(name = "OE", type = OE.class),
        @XmlElement(name = "HTMLBlock", type = HtmlContent.class)
    })
    protected List<Object> oeOrHTMLBlock;
    @XmlAttribute
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger indent;
    @XmlAttribute
    protected String selected;
    @XmlAttribute
    protected String style;
    @XmlAttribute
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger quickStyleIndex;
    @XmlAttribute
    protected String lang;

    /**
     * Gets the value of the childOELayout property.
     * 
     * @return
     *     possible object is
     *     {@link ChildOELayout }
     *     
     */
    public ChildOELayout getChildOELayout() {
        return childOELayout;
    }

    /**
     * Sets the value of the childOELayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChildOELayout }
     *     
     */
    public void setChildOELayout(ChildOELayout value) {
        this.childOELayout = value;
    }

    /**
     * Gets the value of the oeOrHTMLBlock property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oeOrHTMLBlock property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOEOrHTMLBlock().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OE }
     * {@link HtmlContent }
     * 
     * 
     */
    public List<Object> getOEOrHTMLBlock() {
        if (oeOrHTMLBlock == null) {
            oeOrHTMLBlock = new ArrayList<Object>();
        }
        return this.oeOrHTMLBlock;
    }

    /**
     * Gets the value of the indent property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIndent() {
        if (indent == null) {
            return new BigInteger("1");
        } else {
            return indent;
        }
    }

    /**
     * Sets the value of the indent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIndent(BigInteger value) {
        this.indent = value;
    }

    /**
     * Gets the value of the selected property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelected() {
        if (selected == null) {
            return "none";
        } else {
            return selected;
        }
    }

    /**
     * Sets the value of the selected property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelected(String value) {
        this.selected = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStyle() {
        return style;
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyle(String value) {
        this.style = value;
    }

    /**
     * Gets the value of the quickStyleIndex property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getQuickStyleIndex() {
        return quickStyleIndex;
    }

    /**
     * Sets the value of the quickStyleIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setQuickStyleIndex(BigInteger value) {
        this.quickStyleIndex = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

}
