//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.26 at 07:40:13 PM MESZ 
//


package com.setantamedia.fulcrum.microsoft.office.onenote;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * 				Describes a single OneNote page.
 * 			
 * 
 * <p>Java class for Page complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Page">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TagDef" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}TagDef" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="QuickStyleDef" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}QuickStyleDef" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="XPSFile" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}XPSFile" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Meta" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}Meta" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MediaPlaylist" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}MediaPlaylist" minOccurs="0"/>
 *         &lt;element name="PageSettings" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}PageSettings" minOccurs="0"/>
 *         &lt;element name="Title" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}Title" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="Outline" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}Outline"/>
 *           &lt;element name="Image" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}Image"/>
 *           &lt;element name="InkDrawing" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}InkDrawing"/>
 *           &lt;element name="InsertedFile" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}InsertedFile"/>
 *           &lt;element name="MediaFile" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}MediaFile"/>
 *           &lt;element name="FutureObject" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}FutureObject"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://schemas.microsoft.com/office/onenote/2010/onenote}HierarchyObjectAttributes"/>
 *       &lt;attGroup ref="{http://schemas.microsoft.com/office/onenote/2010/onenote}CascadedTextAttributes"/>
 *       &lt;attribute name="dateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="selected" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}Selection" default="none" />
 *       &lt;attribute name="isSubPage" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="pageLevel">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="3"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="isCollapsed" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="isUnread" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isIndexed" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="hasFutureContent" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="stationeryName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Page", propOrder = {
    "tagDef",
    "quickStyleDef",
    "xpsFile",
    "meta",
    "mediaPlaylist",
    "pageSettings",
    "title",
    "outlineOrImageOrInkDrawing"
})
public class Page {

    @XmlElement(name = "TagDef")
    protected List<TagDef> tagDef;
    @XmlElement(name = "QuickStyleDef")
    protected List<QuickStyleDef> quickStyleDef;
    @XmlElement(name = "XPSFile")
    protected List<XPSFile> xpsFile;
    @XmlElement(name = "Meta")
    protected List<Meta> meta;
    @XmlElement(name = "MediaPlaylist")
    protected MediaPlaylist mediaPlaylist;
    @XmlElement(name = "PageSettings")
    protected PageSettings pageSettings;
    @XmlElement(name = "Title")
    protected Title title;
    @XmlElements({
        @XmlElement(name = "InkDrawing", type = InkDrawing.class),
        @XmlElement(name = "Outline", type = Outline.class),
        @XmlElement(name = "InsertedFile", type = InsertedFile.class),
        @XmlElement(name = "Image", type = Image.class),
        @XmlElement(name = "FutureObject", type = FutureObject.class),
        @XmlElement(name = "MediaFile", type = MediaFile.class)
    })
    protected List<PageObject> outlineOrImageOrInkDrawing;
    @XmlAttribute
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateTime;
    @XmlAttribute
    protected String selected;
    @XmlAttribute
    protected Boolean isSubPage;
    @XmlAttribute
    protected Integer pageLevel;
    @XmlAttribute
    protected Boolean isCollapsed;
    @XmlAttribute
    protected Boolean isUnread;
    @XmlAttribute
    protected Boolean isIndexed;
    @XmlAttribute
    protected Boolean hasFutureContent;
    @XmlAttribute
    protected String stationeryName;
    @XmlAttribute(name = "ID")
    protected String id;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModifiedTime;
    @XmlAttribute
    protected Boolean isCurrentlyViewed;
    @XmlAttribute
    protected Boolean isInRecycleBin;
    @XmlAttribute
    protected String style;
    @XmlAttribute
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger quickStyleIndex;
    @XmlAttribute
    protected String lang;

    /**
     * Gets the value of the tagDef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tagDef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTagDef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TagDef }
     * 
     * 
     */
    public List<TagDef> getTagDef() {
        if (tagDef == null) {
            tagDef = new ArrayList<TagDef>();
        }
        return this.tagDef;
    }

    /**
     * Gets the value of the quickStyleDef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the quickStyleDef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQuickStyleDef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QuickStyleDef }
     * 
     * 
     */
    public List<QuickStyleDef> getQuickStyleDef() {
        if (quickStyleDef == null) {
            quickStyleDef = new ArrayList<QuickStyleDef>();
        }
        return this.quickStyleDef;
    }

    /**
     * Gets the value of the xpsFile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the xpsFile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getXPSFile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XPSFile }
     * 
     * 
     */
    public List<XPSFile> getXPSFile() {
        if (xpsFile == null) {
            xpsFile = new ArrayList<XPSFile>();
        }
        return this.xpsFile;
    }

    /**
     * Gets the value of the meta property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the meta property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeta().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Meta }
     * 
     * 
     */
    public List<Meta> getMeta() {
        if (meta == null) {
            meta = new ArrayList<Meta>();
        }
        return this.meta;
    }

    /**
     * Gets the value of the mediaPlaylist property.
     * 
     * @return
     *     possible object is
     *     {@link MediaPlaylist }
     *     
     */
    public MediaPlaylist getMediaPlaylist() {
        return mediaPlaylist;
    }

    /**
     * Sets the value of the mediaPlaylist property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaPlaylist }
     *     
     */
    public void setMediaPlaylist(MediaPlaylist value) {
        this.mediaPlaylist = value;
    }

    /**
     * Gets the value of the pageSettings property.
     * 
     * @return
     *     possible object is
     *     {@link PageSettings }
     *     
     */
    public PageSettings getPageSettings() {
        return pageSettings;
    }

    /**
     * Sets the value of the pageSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link PageSettings }
     *     
     */
    public void setPageSettings(PageSettings value) {
        this.pageSettings = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link Title }
     *     
     */
    public Title getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link Title }
     *     
     */
    public void setTitle(Title value) {
        this.title = value;
    }

    /**
     * Gets the value of the outlineOrImageOrInkDrawing property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outlineOrImageOrInkDrawing property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutlineOrImageOrInkDrawing().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InkDrawing }
     * {@link Outline }
     * {@link InsertedFile }
     * {@link Image }
     * {@link FutureObject }
     * {@link MediaFile }
     * 
     * 
     */
    public List<PageObject> getOutlineOrImageOrInkDrawing() {
        if (outlineOrImageOrInkDrawing == null) {
            outlineOrImageOrInkDrawing = new ArrayList<PageObject>();
        }
        return this.outlineOrImageOrInkDrawing;
    }

    /**
     * Gets the value of the dateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateTime() {
        return dateTime;
    }

    /**
     * Sets the value of the dateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateTime(XMLGregorianCalendar value) {
        this.dateTime = value;
    }

    /**
     * Gets the value of the selected property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelected() {
        if (selected == null) {
            return "none";
        } else {
            return selected;
        }
    }

    /**
     * Sets the value of the selected property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelected(String value) {
        this.selected = value;
    }

    /**
     * Gets the value of the isSubPage property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsSubPage() {
        return isSubPage;
    }

    /**
     * Sets the value of the isSubPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsSubPage(Boolean value) {
        this.isSubPage = value;
    }

    /**
     * Gets the value of the pageLevel property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPageLevel() {
        return pageLevel;
    }

    /**
     * Sets the value of the pageLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPageLevel(Integer value) {
        this.pageLevel = value;
    }

    /**
     * Gets the value of the isCollapsed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsCollapsed() {
        if (isCollapsed == null) {
            return false;
        } else {
            return isCollapsed;
        }
    }

    /**
     * Sets the value of the isCollapsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCollapsed(Boolean value) {
        this.isCollapsed = value;
    }

    /**
     * Gets the value of the isUnread property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsUnread() {
        return isUnread;
    }

    /**
     * Sets the value of the isUnread property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsUnread(Boolean value) {
        this.isUnread = value;
    }

    /**
     * Gets the value of the isIndexed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsIndexed() {
        if (isIndexed == null) {
            return true;
        } else {
            return isIndexed;
        }
    }

    /**
     * Sets the value of the isIndexed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsIndexed(Boolean value) {
        this.isIndexed = value;
    }

    /**
     * Gets the value of the hasFutureContent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isHasFutureContent() {
        if (hasFutureContent == null) {
            return false;
        } else {
            return hasFutureContent;
        }
    }

    /**
     * Sets the value of the hasFutureContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasFutureContent(Boolean value) {
        this.hasFutureContent = value;
    }

    /**
     * Gets the value of the stationeryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStationeryName() {
        return stationeryName;
    }

    /**
     * Sets the value of the stationeryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStationeryName(String value) {
        this.stationeryName = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the lastModifiedTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * Sets the value of the lastModifiedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModifiedTime(XMLGregorianCalendar value) {
        this.lastModifiedTime = value;
    }

    /**
     * Gets the value of the isCurrentlyViewed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsCurrentlyViewed() {
        if (isCurrentlyViewed == null) {
            return false;
        } else {
            return isCurrentlyViewed;
        }
    }

    /**
     * Sets the value of the isCurrentlyViewed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCurrentlyViewed(Boolean value) {
        this.isCurrentlyViewed = value;
    }

    /**
     * Gets the value of the isInRecycleBin property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsInRecycleBin() {
        if (isInRecycleBin == null) {
            return false;
        } else {
            return isInRecycleBin;
        }
    }

    /**
     * Sets the value of the isInRecycleBin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsInRecycleBin(Boolean value) {
        this.isInRecycleBin = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStyle() {
        return style;
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyle(String value) {
        this.style = value;
    }

    /**
     * Gets the value of the quickStyleIndex property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getQuickStyleIndex() {
        return quickStyleIndex;
    }

    /**
     * Sets the value of the quickStyleIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setQuickStyleIndex(BigInteger value) {
        this.quickStyleIndex = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

}
