//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.26 at 07:40:13 PM MESZ 
//


package com.setantamedia.fulcrum.microsoft.office.onenote;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Base for page objects that support media and noteflags.
 * 			
 * 
 * <p>Java class for PageObjectTagable complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PageObjectTagable">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.microsoft.com/office/onenote/2010/onenote}PageObject">
 *       &lt;sequence>
 *         &lt;element name="MediaIndex" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}MediaIndex" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Tag" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}Tag" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="OutlookTask" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}OutlookTask"/>
 *           &lt;element name="Tag" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}Tag" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PageObjectTagable", propOrder = {
    "rest"
})
@XmlSeeAlso({
    InkDrawing.class,
    FutureObject.class,
    InsertedFile.class,
    Image.class
})
public class PageObjectTagable
    extends PageObject
{

    @XmlElementRefs({
        @XmlElementRef(name = "MediaIndex", namespace = "http://schemas.microsoft.com/office/onenote/2010/onenote", type = JAXBElement.class),
        @XmlElementRef(name = "Tag", namespace = "http://schemas.microsoft.com/office/onenote/2010/onenote", type = JAXBElement.class),
        @XmlElementRef(name = "OutlookTask", namespace = "http://schemas.microsoft.com/office/onenote/2010/onenote", type = JAXBElement.class)
    })
    protected List<JAXBElement<?>> rest;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "Tag" is used by two different parts of a schema. See: 
     * line 316 of file:/C:/Users/colin/git/fulcrum3/resources/xml/OneNote2010.xsd
     * line 308 of file:/C:/Users/colin/git/fulcrum3/resources/xml/OneNote2010.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the rest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link MediaIndex }{@code >}
     * {@link JAXBElement }{@code <}{@link Tag }{@code >}
     * {@link JAXBElement }{@code <}{@link OutlookTask }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getRest() {
        if (rest == null) {
            rest = new ArrayList<JAXBElement<?>>();
        }
        return this.rest;
    }

}
