//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.26 at 07:40:13 PM MESZ 
//


package com.setantamedia.fulcrum.microsoft.office.onenote;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Settings for the page.
 * 			
 * 
 * <p>Java class for PageSettings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PageSettings">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PageSize" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}PageSize" minOccurs="0"/>
 *         &lt;element name="RuleLines" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}RuleLines" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="RTL" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="color" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}COLOR" default="automatic" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PageSettings", propOrder = {
    "pageSize",
    "ruleLines"
})
public class PageSettings {

    @XmlElement(name = "PageSize")
    protected PageSize pageSize;
    @XmlElement(name = "RuleLines")
    protected RuleLines ruleLines;
    @XmlAttribute(name = "RTL")
    protected Boolean rtl;
    @XmlAttribute
    protected String color;

    /**
     * Gets the value of the pageSize property.
     * 
     * @return
     *     possible object is
     *     {@link PageSize }
     *     
     */
    public PageSize getPageSize() {
        return pageSize;
    }

    /**
     * Sets the value of the pageSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link PageSize }
     *     
     */
    public void setPageSize(PageSize value) {
        this.pageSize = value;
    }

    /**
     * Gets the value of the ruleLines property.
     * 
     * @return
     *     possible object is
     *     {@link RuleLines }
     *     
     */
    public RuleLines getRuleLines() {
        return ruleLines;
    }

    /**
     * Sets the value of the ruleLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleLines }
     *     
     */
    public void setRuleLines(RuleLines value) {
        this.ruleLines = value;
    }

    /**
     * Gets the value of the rtl property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRTL() {
        if (rtl == null) {
            return false;
        } else {
            return rtl;
        }
    }

    /**
     * Sets the value of the rtl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRTL(Boolean value) {
        this.rtl = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        if (color == null) {
            return "automatic";
        } else {
            return color;
        }
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

}
