//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.26 at 07:40:13 PM MESZ 
//


package com.setantamedia.fulcrum.microsoft.office.onenote;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			
 * 
 * <p>Java class for UnfiledNotes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UnfiledNotes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Section" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}Section" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isCurrentlyViewed" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="ID" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}ObjectID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UnfiledNotes", propOrder = {
    "section"
})
public class UnfiledNotes {

    @XmlElement(name = "Section")
    protected Section section;
    @XmlAttribute
    protected Boolean isCurrentlyViewed;
    @XmlAttribute(name = "ID")
    protected String id;

    /**
     * Gets the value of the section property.
     * 
     * @return
     *     possible object is
     *     {@link Section }
     *     
     */
    public Section getSection() {
        return section;
    }

    /**
     * Sets the value of the section property.
     * 
     * @param value
     *     allowed object is
     *     {@link Section }
     *     
     */
    public void setSection(Section value) {
        this.section = value;
    }

    /**
     * Gets the value of the isCurrentlyViewed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsCurrentlyViewed() {
        if (isCurrentlyViewed == null) {
            return false;
        } else {
            return isCurrentlyViewed;
        }
    }

    /**
     * Sets the value of the isCurrentlyViewed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCurrentlyViewed(Boolean value) {
        this.isCurrentlyViewed = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

}
