//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.26 at 07:40:13 PM MESZ 
//


package com.setantamedia.fulcrum.microsoft.office.onenote;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Defines a single Microsoft Document Imaging file.
 * 			
 * 
 * <p>Java class for XPSFile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XPSFile">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="File" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}FilePath"/>
 *         &lt;element name="Data" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="CallbackID" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}CallbackID"/>
 *       &lt;/choice>
 *       &lt;attribute name="xpsFileIndex" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="idDocument" type="{http://schemas.microsoft.com/office/onenote/2010/onenote}GUID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XPSFile", propOrder = {
    "file",
    "data",
    "callbackID"
})
public class XPSFile {

    @XmlElement(name = "File")
    protected FilePath file;
    @XmlElement(name = "Data")
    protected byte[] data;
    @XmlElement(name = "CallbackID")
    protected CallbackID callbackID;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger xpsFileIndex;
    @XmlAttribute
    protected String idDocument;

    /**
     * Gets the value of the file property.
     * 
     * @return
     *     possible object is
     *     {@link FilePath }
     *     
     */
    public FilePath getFile() {
        return file;
    }

    /**
     * Sets the value of the file property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilePath }
     *     
     */
    public void setFile(FilePath value) {
        this.file = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setData(byte[] value) {
        this.data = ((byte[]) value);
    }

    /**
     * Gets the value of the callbackID property.
     * 
     * @return
     *     possible object is
     *     {@link CallbackID }
     *     
     */
    public CallbackID getCallbackID() {
        return callbackID;
    }

    /**
     * Sets the value of the callbackID property.
     * 
     * @param value
     *     allowed object is
     *     {@link CallbackID }
     *     
     */
    public void setCallbackID(CallbackID value) {
        this.callbackID = value;
    }

    /**
     * Gets the value of the xpsFileIndex property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getXpsFileIndex() {
        return xpsFileIndex;
    }

    /**
     * Sets the value of the xpsFileIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setXpsFileIndex(BigInteger value) {
        this.xpsFileIndex = value;
    }

    /**
     * Gets the value of the idDocument property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdDocument() {
        return idDocument;
    }

    /**
     * Sets the value of the idDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdDocument(String value) {
        this.idDocument = value;
    }

}
